import type { Compact } from "./compact";

/** Pack 4 — Deeper questions across every area of the product. */
export const PACK_EXTRA: Compact[] = [
  /* ——— Targeting nuance ——— */
  { id: "x-competitors", q: "Can I find my competitors?", c: "discovery", k: "competitor competitors rival market same",
    a: ["Yes — search your own category and market, and the results are the businesses operating alongside you."], f: ["x-market-size", "lead-info", "ex-location"] },
  { id: "x-market-size", q: "Can I size a market?", c: "discovery", k: "market size how many count research total",
    a: ["Run a search for a category and location and the result count tells you how many listed businesses Zybble found there.", "Add filters to count only the ones with websites or strong ratings."], f: ["ex-filters", "ex-quantity", "x-research"] },
  { id: "x-research", q: "Can I use it for market research?", c: "discovery", k: "research market analysis study explore insight",
    a: ["Yes — category, rating, review volume, and website presence across a market give you a quick read on how competitive and how digitally mature it is."], f: ["x-market-size", "how-ai", "ex-rating"] },
  { id: "x-territory", q: "Can I plan sales territories?", c: "discovery", k: "territory region split area assign map coverage",
    a: ["Leads carry addresses and coordinates, so you can split a list geographically and export each slice separately."], f: ["ex-coords", "csv-export", "ex-multi-city"] },
  { id: "x-franchise", q: "Can I find franchise locations?", c: "discovery", k: "franchise chain locations branches multiple stores",
    a: ["Describe the business type and area; each physical location that's publicly listed comes back as its own record with its own address and phone."], f: ["dedupe", "ex-location", "lead-info"] },
  { id: "x-new-businesses", q: "Can I find newly opened businesses?", c: "discovery", k: "new opened recent fresh startups just",
    a: ["Zybble returns what's publicly listed at search time. Low review counts often signal newer businesses — a useful signal once results are in."], f: ["ex-reviews", "data-freshness", "rerun-search"] },
  { id: "x-low-rating", q: "Can I target low-rated businesses?", c: "discovery", k: "low rating bad poor struggling improve reputation",
    a: ["Ratings and review counts come with every lead, so you can sort the list toward businesses that may need help with their reputation."], f: ["ex-rating", "l-segment", "how-ai"] },
  { id: "x-no-website", q: "Can I target businesses lacking a web presence?", c: "discovery", k: "no website missing web presence design build",
    a: ["Every lead shows whether a website was detected, so a list can be segmented toward businesses without one — a common angle for web and marketing services."], f: ["ex-website", "l-segment", "ex-filters"] },
  { id: "x-by-size", q: "Can I filter by company size?", c: "discovery", k: "size employees headcount small large revenue",
    a: ["The supported filters are rating, website, and phone. Review volume and category are useful proxies for scale once results are in."], f: ["ex-filters", "ex-reviews", "lead-info"] },
  { id: "x-keywords", q: "Can I search by keyword?", c: "discovery", k: "keyword term phrase specific name brand",
    a: ["You describe the business in natural language, so specific wording like “cosmetic dentists” or “boutique hotels” narrows the category directly."], f: ["search-phrasing", "ex-category-field", "what-can-search"] },
  { id: "x-exclude", q: "Can I exclude certain businesses?", c: "discovery", k: "exclude remove without except filter out skip",
    a: ["Sharpen the request itself — a narrower category and location gets you closer — then use tags and status to set aside anything you don't want."], f: ["tags-notes", "l-segment", "search-phrasing"] },
  { id: "x-radius", q: "Can I search within a radius?", c: "discovery", k: "radius near around distance miles km nearby",
    a: ["Describe the area you want — a city, a district, a region. Coordinates on each lead let you measure distance after the fact."], f: ["ex-location", "ex-coords", "x-territory"] },
  { id: "x-rural", q: "Does it work for small towns?", c: "discovery", k: "rural small town village countryside sparse",
    a: ["You can search any location you describe. Smaller markets simply have fewer listed businesses, so expect smaller result counts."], f: ["ex-location", "ex-quantity-small", "data-quality"] },
  { id: "x-seasonal", q: "Can I re-check a market later?", c: "discovery", k: "seasonal later again monitor change track",
    a: ["Yes — re-run the search whenever you want an updated view. Each run draws on your monthly allowance."], f: ["rerun-search", "data-freshness", "limits"] },
  { id: "x-save-query", q: "Can I reuse a search request?", c: "discovery", k: "reuse save template repeat query again",
    a: ["Requests are plain sentences, so keeping your best-performing phrasing and running it against a new city takes seconds."], f: ["search-phrasing", "ex-multi-city", "rerun-search"] },

  /* ——— Data depth ——— */
  { id: "x-d-name", q: "How are business names formatted?", c: "data", k: "name formatted title business official",
    a: ["Leads use the business name as it appears in its public listing."], f: ["lead-info", "d-source-info", "export-fields"] },
  { id: "x-d-multiple-phones", q: "What if a business has several phone numbers?", c: "data", k: "multiple phones numbers several second",
    a: ["The phone captured is the one published on the business's public listing."], f: ["d-phones", "partial-data", "lead-info"] },
  { id: "x-d-generic-email", q: "Are the emails generic or personal?", c: "data", k: "generic personal info@ contact role decision maker",
    a: ["Emails come from what a business publishes publicly, which is usually a general business address rather than a named individual."], f: ["d-emails", "gs-consumers", "d-email-rate"] },
  { id: "x-d-decision-maker", q: "Can I get the owner's contact?", c: "data", k: "owner ceo decision maker contact person name",
    a: ["Zybble surfaces the **business's** public contact details rather than named individuals."], f: ["gs-consumers", "d-emails", "lead-info"] },
  { id: "x-d-normalized", q: "Is the data cleaned up?", c: "data", k: "clean normalized formatted tidy structured messy",
    a: ["Yes — results are processed and deduplicated into consistent rows rather than raw listings."], f: ["dedupe", "search-process", "csv-export"] },
  { id: "x-d-language", q: "What language is the data in?", c: "data", k: "language english translated local foreign",
    a: ["Business details appear as they're published in their public listings."], f: ["gs-countries", "lead-info", "data-quality"] },
  { id: "x-d-photos", q: "Are business photos included?", c: "data", k: "photo photos image picture logo",
    a: ["The documented lead fields cover identity, contact, location, reputation, hours, price level, services and amenities, and source information."], f: ["d-fields-full", "lead-info", "partial-data"] },
  { id: "x-d-closed", q: "What about closed businesses?", c: "data", k: "closed permanently shut out of business defunct",
    a: ["Results reflect current public listings at search time, which is why re-running a search later can return an updated picture.", "Verify anything critical before outreach."], f: ["data-freshness", "d-verify", "rerun-search"] },

  /* ——— AI depth ——— */
  { id: "x-ai-per-lead", q: "Does AI run on every lead automatically?", c: "ai", k: "automatic every all run automatically each",
    a: ["Analysis is something you open for a business you care about, rather than a blanket pass over everything."], f: ["ai-bulk", "ai-summary", "ai-availability"] },
  { id: "x-ai-score", q: "Does it score or rank leads?", c: "ai", k: "score ranking rank grade priority best quality",
    a: ["Zybble AI produces a short written read of what the data suggests — local presence, review activity, website status, and outreach angles."], f: ["ai-summary", "ai-outreach", "ai-limits"] },
  { id: "x-ai-compare", q: "Can AI compare two businesses?", c: "ai", k: "compare two versus difference between which",
    a: ["Summaries are generated per business. Reading two side by side gives you the comparison, grounded in each one's own data."], f: ["ai-summary", "x-ai-score", "ai-limits"] },
  { id: "x-ai-trust", q: "How much should I trust AI summaries?", c: "ai", k: "trust reliable believe accurate confidence wrong",
    a: ["Treat them as an informed starting point. They're generated from available business data and marked as AI generated — verify anything you'll act on."], f: ["ai-limits", "d-verify", "how-ai"] },
  { id: "x-ai-data-used", q: "What data does the AI read?", c: "ai", k: "reads uses input source based on what",
    a: ["The available business data for that lead — the same fields you can see, like category, rating, review count, and whether a website was detected."], f: ["lead-info", "ai-limits", "lead-sources"] },
  { id: "x-ai-writes-emails", q: "Does it write outreach emails?", c: "ai", k: "write email copy message draft template generate",
    a: ["Zybble AI's documented job is interpreting searches and analyzing businesses — including possible outreach angles you can build your own message from."], f: ["ai-outreach", "ai-summary", "csv-export"] },
  { id: "x-ai-cost", q: "Does using AI cost extra?", c: "ai", k: "cost extra charge credits price ai usage",
    a: ["No — Zybble AI is included in the plan price on Growth, Agency, and Scale."], cta: ["View pricing", "/#pricing"], f: ["ai-availability", "p-hidden-fees", "plan-growth"] },

  /* ——— Workflow ——— */
  { id: "x-w-team-share", q: "Can teammates see my lists?", c: "team", k: "share see teammates visible collaborate together",
    a: ["Team plans put your members in one account — Agency includes 3, Scale includes 5 — with client workspaces keeping separate work separate."], f: ["team-use", "workspaces", "plan-agency"] },
  { id: "x-w-notes", q: "Can I leave notes on a lead?", c: "lists", k: "note notes comment annotate remark",
    a: ["Yes — leads carry tags, status, and notes so context travels with the record."], f: ["tags-notes", "l-status", "lead-lists"] },
  { id: "x-w-progress", q: "How do I track who I've contacted?", c: "lists", k: "contacted track progress followed up done status",
    a: ["Use the **Contacted** status, alongside New and Enriched, so the list always reflects reality."], f: ["l-status", "tags-notes", "l-crm"] },
  { id: "x-w-dupe-lists", q: "What if two lists overlap?", c: "lists", k: "overlap duplicate across lists same twice",
    a: ["Deduplication happens within a search. Across lists, tags and status help you spot a business you're already working."], f: ["dedupe", "tags-notes", "l-segment"] },
  { id: "x-w-big-list", q: "How do I work a large list?", c: "lists", k: "large big many overwhelming thousands approach",
    a: ["Segment first — by rating, website presence, or tag — then analyze the top slice with AI and export it as your first outreach batch."], f: ["l-segment", "ai-bulk", "export-select"] },

  /* ——— Export depth ——— */
  { id: "x-e-open-excel", q: "Will the CSV open in Excel or Sheets?", c: "export", k: "excel sheets google open numbers spreadsheet",
    a: ["Yes — CSV is the standard spreadsheet format and opens in Excel, Google Sheets, and Numbers."], f: ["e-formats", "export-fields", "e-crm"] },
  { id: "x-e-columns", q: "Can I choose the column order?", c: "export", k: "columns order choose arrange customize fields",
    a: ["You pick which fields to include at export time — business, phone, email, website, address, rating."], f: ["export-fields", "export-select", "csv-export"] },
  { id: "x-e-repeat", q: "Can I export the same list twice?", c: "export", k: "again twice repeat re-export multiple times",
    a: ["Export is included on every plan, so you can pull an updated file whenever a list changes."], f: ["e-limit", "csv-export", "l-segment"] },
  { id: "x-e-api", q: "Is there an API?", c: "export", k: "api integration webhook zapier developer connect",
    a: ["The documented way to move leads out of Zybble is **CSV export**, available on every plan."], f: ["csv-export", "e-crm", "contact"] },

  /* ——— Pricing scenarios ——— */
  { id: "x-p-agency-clients", q: "How many clients can I serve on Agency?", c: "pricing", k: "clients how many agency serve accounts",
    a: ["Agency ($99/mo) includes client workspaces, 3 team members, and 15,000 leads a month — the lead allowance is usually the practical constraint."], cta: ["View pricing", "/#pricing"], f: ["workspaces", "plan-agency", "u-shared"] },
  { id: "x-p-which-volume", q: "How do I know how many leads I need?", c: "pricing", k: "how many need estimate volume guess calculate",
    a: ["Work back from outreach: a few hundred leads a month sits inside Growth's 5,000; multi-market or multi-client work usually lands on Agency or Scale."], cta: ["View pricing", "/#pricing"], f: ["p-compare", "which-plan", "limits"] },
  { id: "x-p-start-small", q: "Can I start small and grow?", c: "pricing", k: "start small grow scale later increase gradually",
    a: ["Yes — plans are monthly, so you can start on Free or Growth and move up whenever your volume does."], f: ["gs-upgrade-later", "plan-free", "p-compare"] },
  { id: "x-p-pause", q: "Can I pause my subscription?", c: "billing", k: "pause hold suspend temporarily stop break",
    a: ["Plans are monthly with no long-term commitment, and cancelling takes effect at the end of the current period — so you can stop and return later."], f: ["billing", "b-cancel-effect", "gs-upgrade-later"] },
  { id: "x-p-value", q: "What am I paying for exactly?", c: "pricing", k: "paying value what get worth included",
    a: ["The monthly lead allowance plus the features at that tier — AI, unlimited lists, team seats, client workspaces, and priority processing at the top."], cta: ["View pricing", "/#pricing"], f: ["p-compare", "p-per-lead", "pricing-work"] },
  { id: "x-p-free-forever", q: "Is the Free plan time-limited?", c: "pricing", k: "free forever expire trial days limited time",
    a: ["Free is listed as a **$0/mo plan** with 50 leads a month — a tier, not a countdown."], cta: ["View pricing", "/#pricing"], f: ["plan-free", "gs-trial", "limits"] },
  { id: "x-p-currency", q: "What currency are prices in?", c: "billing", k: "currency usd dollars eur local money",
    a: ["Prices are listed in US dollars — $0, $49, $99, and $199 per month."], cta: ["View pricing", "/#pricing"], f: ["pricing-work", "b-payment", "p-hidden-fees"] },
  { id: "x-p-tax", q: "Are taxes included?", c: "billing", k: "tax vat gst included sales",
    a: ["The plan prices shown are the listed monthly rates. For a billing specific to your region, the contact page reaches a person."], cta: ["Contact us", "/contact"], f: ["b-payment", "contact", "p-hidden-fees"] },
  { id: "x-p-invoice", q: "Can I get an invoice?", c: "billing", k: "invoice receipt bill accounting expense",
    a: ["Billing runs monthly through the payment provider. For a specific invoicing need, ask through the contact page."], cta: ["Contact us", "/contact"], f: ["b-payment", "contact", "billing"] },

  /* ——— Company & trust ——— */
  { id: "x-c-what-makes", q: "What makes Zybble different?", c: "product", k: "different unique better why choose special advantage",
    a: ["One sentence in, a structured lead list out — search, processing, deduplication, enrichment, and AI analysis in one place, with CSV export on every plan."], f: ["gs-vs-scraping", "gs-vs-lists", "how-find"] },
  { id: "x-c-support-channels", q: "How do I reach you?", c: "support", k: "reach contact email phone chat channels talk",
    a: ["Through the contact page, or by email at **tejassutar.business@gmail.com**. A person replies within about one business day."], cta: ["Contact us", "/contact"], f: ["contact", "sup-response", "gs-demo"] },
  { id: "x-c-docs", q: "Is there documentation?", c: "support", k: "docs documentation guide help manual tutorial",
    a: ["This assistant and the FAQ cover how discovery, data, AI, lists, exports, pricing, and workspaces work. For anything else, the contact page reaches a person."], cta: ["Contact us", "/contact"], f: ["contact", "how-find", "pricing-work"] },
  { id: "x-c-assistant", q: "What can you help with?", c: "support", k: "you help assistant capabilities topics what",
    a: ["Lead discovery, lead data, Zybble AI, lists, exports, pricing and plans, limits, teams, client workspaces, billing, and data handling.", "Browse all topics from the button below any time."], f: ["how-find", "pricing-work", "contact"] },

  /* ——— More industries ——— */
  { id: "i-coffee", q: "Can it find coffee shops?", c: "discovery", k: "coffee cafe shop espresso bakery",
    a: ["Yes. Try: “Find 200 coffee shops in Seattle rated above 4.”"], f: ["ex-filters", "lead-info", "ex-restaurants"] },
  { id: "i-auto", q: "Can it find auto repair shops?", c: "discovery", k: "auto car repair mechanic garage dealership tire",
    a: ["Yes — mechanics, body shops, tire centers, and dealerships are all describable categories.", "Try: “Find 250 auto repair shops in Houston with phone numbers.”"], f: ["ex-filters", "lead-info", "example-search"] },
  { id: "i-accountants", q: "Can it find accountants?", c: "discovery", k: "accountant cpa bookkeeping tax financial firm",
    a: ["Yes. Try: “Find 150 accounting firms in Boston with websites.”"], f: ["ex-website", "lead-info", "ex-legal"] },
  { id: "i-insurance", q: "Can it find insurance agencies?", c: "discovery", k: "insurance agent broker agency policy",
    a: ["Yes. Try: “Find 200 insurance agencies in Dallas rated above 4.”"], f: ["ex-rating", "lead-info", "csv-export"] },
  { id: "i-construction", q: "Can it find construction companies?", c: "discovery", k: "construction builder general contractor remodel renovation",
    a: ["Yes. Try: “Find 200 general contractors in Denver with websites.”"], f: ["ex-contractors", "ex-website", "lead-info"] },
  { id: "i-cleaning", q: "Can it find cleaning companies?", c: "discovery", k: "cleaning janitorial maid housekeeping commercial",
    a: ["Yes. Try: “Find 150 commercial cleaning companies in Chicago.”"], f: ["lead-info", "ex-filters", "csv-export"] },
  { id: "i-landscaping", q: "Can it find landscaping businesses?", c: "discovery", k: "landscaping lawn garden yard tree outdoor",
    a: ["Yes. Try: “Find 200 landscaping companies in Atlanta with phone numbers.”"], f: ["ex-filters", "lead-info", "example-search"] },
  { id: "i-photographers", q: "Can it find photographers?", c: "discovery", k: "photographer photography studio wedding video",
    a: ["Yes. Try: “Find 150 wedding photographers in Austin with websites.”"], f: ["ex-website", "lead-info", "i-events"] },
  { id: "i-events", q: "Can it find event venues or planners?", c: "discovery", k: "event venue planner wedding catering party banquet",
    a: ["Yes — venues, planners, and caterers are all describable categories.", "Try: “Find 100 event venues in Nashville rated above 4.”"], f: ["ex-rating", "lead-info", "i-photographers"] },
  { id: "i-schools", q: "Can it find schools or tutoring centers?", c: "discovery", k: "school tutoring education daycare preschool academy training",
    a: ["Yes. Try: “Find 150 tutoring centers in Phoenix with websites.”"], f: ["ex-website", "lead-info", "example-search"] },
  { id: "i-it", q: "Can it find IT or web design companies?", c: "discovery", k: "it web design software development agency tech msp",
    a: ["Yes. Try: “Find 200 web design agencies in Portland with websites.”"], f: ["ex-agencies", "ex-website", "lead-info"] },
  { id: "i-staffing", q: "Can it find staffing agencies?", c: "discovery", k: "staffing recruiting recruitment hr employment temp",
    a: ["Yes. Try: “Find 150 staffing agencies in Chicago rated above 4.”"], f: ["ex-rating", "ex-agencies", "lead-info"] },
  { id: "i-pharmacies", q: "Can it find pharmacies or opticians?", c: "discovery", k: "pharmacy optician optometrist chemist drugstore eyewear",
    a: ["Yes — both are business categories you can describe.", "Try: “Find 200 independent pharmacies in Florida with phone numbers.”"], f: ["ex-medical", "ex-filters", "lead-info"] },
  { id: "i-wellness", q: "Can it find chiropractors or therapists?", c: "discovery", k: "chiropractor physical therapy massage wellness mental health",
    a: ["Yes. Try: “Find 150 chiropractors in San Diego rated above 4.5.”"], f: ["ex-medical", "ex-rating", "lead-info"] },
  { id: "i-pets", q: "Can it find pet businesses?", c: "discovery", k: "pet grooming vet kennel boarding dog animal",
    a: ["Yes — groomers, boarding, and veterinary clinics all work.", "Try: “Find 150 pet groomers in Denver with websites.”"], f: ["ex-medical", "ex-website", "lead-info"] },
  { id: "i-breweries", q: "Can it find breweries or wineries?", c: "discovery", k: "brewery winery distillery taproom beer wine",
    a: ["Yes. Try: “Find 100 breweries in Colorado rated above 4.”"], f: ["ex-rating", "ex-restaurants", "lead-info"] },
  { id: "i-moving", q: "Can it find moving or storage companies?", c: "discovery", k: "moving movers storage logistics haul transport",
    a: ["Yes. Try: “Find 150 moving companies in Phoenix with phone numbers.”"], f: ["ex-filters", "lead-info", "csv-export"] },
  { id: "i-print", q: "Can it find print or sign shops?", c: "discovery", k: "print printing sign signage banner promotional",
    a: ["Yes. Try: “Find 150 print shops in Los Angeles with websites.”"], f: ["ex-website", "lead-info", "ex-retail"] },
  { id: "i-seniorcare", q: "Can it find senior care facilities?", c: "discovery", k: "senior care nursing home assisted living elderly",
    a: ["Yes. Try: “Find 100 assisted living facilities in Arizona rated above 4.”"], f: ["ex-medical", "ex-rating", "lead-info"] },
  { id: "i-security", q: "Can it find security companies?", c: "discovery", k: "security guard alarm surveillance protection",
    a: ["Yes. Try: “Find 150 security companies in Houston with websites.”"], f: ["ex-website", "lead-info", "i-it"] },
];
