import type { Compact } from "./compact";

/** Pack 2 — Lead data, Zybble AI, lead lists, and exports. */
export const PACK_DATA_AI: Compact[] = [
  /* ——— Contact data ——— */
  { id: "d-emails", q: "Do leads include email addresses?", c: "data", k: "email emails address contact mail",
    a: ["Yes, when they're **publicly available**. Email data is included on every plan, including Free.", "Where no public email exists, the field stays empty rather than being guessed."],
    f: ["d-email-rate", "enrichment-data", "partial-data"] },
  { id: "d-email-rate", q: "Will every lead have an email?", c: "data", k: "every all emails coverage how many percent",
    a: ["No — emails appear where a business publishes one. Phone numbers and websites are more consistently available.", "You can segment a list by what's actually present before starting outreach."],
    f: ["tags-notes", "d-emails", "partial-data"] },
  { id: "d-phones", q: "Do leads include phone numbers?", c: "data", k: "phone number call telephone contact",
    a: ["Yes — phone data is part of every plan, including Free."],
    f: ["d-emails", "lead-info", "export-fields"] },
  { id: "d-websites", q: "Do leads include websites?", c: "data", k: "website url site domain link web",
    a: ["Yes — the business website is captured where one is detected, and “has a website” works as a search filter too."],
    f: ["ex-website", "lead-info", "ex-filters"] },
  { id: "d-social", q: "Are social profiles included?", c: "data", k: "social instagram facebook linkedin profiles",
    a: ["Leads are built from public business listings, the business website, and public profiles. What surfaces per lead depends on that available data.", "The core fields you can count on are name, category, address, phone, website, rating, reviews, hours, and coordinates."],
    f: ["lead-info", "lead-sources", "partial-data"] },
  { id: "d-address", q: "What location detail do I get?", c: "data", k: "address street location country where map",
    a: ["Full address, country, and coordinates — enough to map leads or split them by territory."],
    f: ["ex-coords", "lead-info", "ex-location"] },
  { id: "d-fields-full", q: "Show me the full field list", c: "data", k: "fields all list complete every columns",
    a: ["- Name, category, business types", "- Address, country, coordinates", "- Phone, website, email when public", "- Rating and review count", "- Hours, price level, services and amenities where available", "- Source information"],
    f: ["export-fields", "lead-sources", "partial-data"] },
  { id: "d-source-info", q: "Can I see where a lead came from?", c: "data", k: "source origin where from provenance reference",
    a: ["Yes — source information travels with the lead, so you can trace a record back to the public listing it came from."],
    f: ["lead-sources", "data-quality", "lead-info"] },
  { id: "d-verify", q: "Should I verify leads before outreach?", c: "data", k: "verify check confirm accurate trust validate",
    a: ["Yes. Business details change, and AI summaries are interpretations of available data — treat both as a strong starting point, then confirm anything critical."],
    f: ["data-quality", "ai-limits", "how-ai"] },
  { id: "d-duplicates-lists", q: "What if the same business appears twice?", c: "data", k: "duplicate twice repeat same again overlap",
    a: ["Deduplication runs as part of every search, so results arrive cleaned rather than raw."],
    f: ["dedupe", "search-process", "data-quality"] },

  /* ——— Zybble AI ——— */
  { id: "ai-what", q: "What exactly does Zybble AI do?", c: "ai", k: "ai what does do role purpose",
    a: ["Two things: it **interprets your request** into a structured search, and it **analyzes businesses** it finds.", "It doesn't invent leads — the businesses come from real public data."],
    f: ["ai-discovery", "ai-summary", "ai-limits"] },
  { id: "ai-summary", q: "What's in an AI summary?", c: "ai", k: "summary analysis insight output result says",
    a: ["A short read on what the data suggests — local presence, review activity, whether a website was detected, and possible outreach angles.", "Summaries are clearly marked as AI generated."],
    f: ["ai-limits", "ai-outreach", "ai-availability"] },
  { id: "ai-outreach", q: "Can AI suggest outreach angles?", c: "ai", k: "outreach angle pitch approach message idea",
    a: ["It can point out opportunities visible in the data — strong review volume, a detected website, or a notable local presence.", "It's a prompt for your judgment, not a script to send as-is."],
    f: ["ai-limits", "ai-summary", "d-verify"] },
  { id: "ai-limits", q: "What are the limits of the AI?", c: "ai", k: "limits limitations wrong accurate trust hallucinate",
    a: ["Zybble AI only works from the **available business data** — it can't confirm facts beyond that source, so verify before you act.", "It's an interpretation layer, not a verification service."],
    f: ["d-verify", "ai-summary", "how-ai"] },
  { id: "ai-free-plan", q: "Is AI included on the Free plan?", c: "ai", k: "free ai included plan available",
    a: ["Yes — Zybble AI is included on **every plan, including Free**. The Free plan still caps volume at 50 leads a month and 1 list."],
    cta: ["View pricing", "/#pricing"], f: ["ai-availability", "plan-growth", "plan-free"] },
  { id: "ai-bulk", q: "Can AI analyze a whole list?", c: "ai", k: "bulk all many list batch every",
    a: ["Analysis runs per business, so you can work through the leads that matter most in a list rather than spending it everywhere."],
    f: ["ai-summary", "lead-lists", "ai-availability"] },
  { id: "ai-language", q: "Do I need to write prompts?", c: "ai", k: "prompt prompting engineering write phrase",
    a: ["No prompt engineering — write the request the way you'd say it out loud. Zybble AI handles turning it into a structured search."],
    f: ["search-phrasing", "example-search", "ai-discovery"] },
  { id: "ai-which-model", q: "Which AI does Zybble use?", c: "ai", k: "model deepseek which engine technology provider",
    a: ["Zybble AI uses **DeepSeek V3.2** for search interpretation, lead analysis, and this assistant. Requests run through Zybble's own secure backend — you never need an AI account, sign-in, or API key. It reads only the available business data and labels its output as AI generated."],
    f: ["ai-limits", "how-ai", "security"] },
  { id: "ai-off", q: "Can I skip the AI features?", c: "ai", k: "off disable skip without turn manual",
    a: ["You can use Zybble purely as a discovery and export tool — run searches, save lists, export CSV — and never open an AI summary."],
    f: ["csv-export", "how-find", "plan-free"] },

  /* ——— Lists & organization ——— */
  { id: "l-create", q: "How do I create a lead list?", c: "lists", k: "create make new list add save",
    a: ["Save a search result into a list and give it a name — “Austin Dentists”, for example. From there you can tag and work the leads."],
    f: ["save-results", "tags-notes", "unlimited-lists"] },
  { id: "l-move", q: "Can I move leads between lists?", c: "lists", k: "move transfer between organize reorganize",
    a: ["Lists are the organizing layer for your leads, with tags and status on each record so you can reshape a list as your campaign changes."],
    f: ["tags-notes", "lead-lists", "l-segment"] },
  { id: "l-segment", q: "Can I segment a list?", c: "lists", k: "segment filter split slice group subset",
    a: ["Yes — tags like **New**, **High rating**, and **Website** carry counts, so a segment is one click and exports respect your selection."],
    f: ["tags-notes", "csv-export", "export-select"] },
  { id: "l-status", q: "Can I track lead status?", c: "lists", k: "status track progress contacted pipeline stage",
    a: ["Each lead carries a status — **New**, **Enriched**, **Contacted** — so a list shows where every prospect actually stands."],
    f: ["tags-notes", "l-segment", "l-crm"] },
  { id: "l-crm", q: "Is this a CRM?", c: "lists", k: "crm pipeline salesforce hubspot replace",
    a: ["Zybble is a lead **discovery** tool with light organization — lists, tags, and status. For full pipeline management, export to CSV and bring the leads into your CRM."],
    f: ["csv-export", "l-status", "lead-lists"] },
  { id: "l-delete", q: "Can I delete leads or lists?", c: "lists", k: "delete remove clear erase",
    a: ["Yes — you can delete individual searches, lists, or your entire account. Deleting an account removes your searches, lists, and exports."],
    f: ["security", "lead-lists", "acct-delete"] },
  { id: "l-count", q: "How many leads fit in one list?", c: "lists", k: "many size capacity big large maximum",
    a: ["Lists aren't the constraint — your **monthly lead allowance** is. Free covers 50 leads a month; Scale covers 50,000."],
    f: ["limits", "unlimited-lists", "pricing-work"] },

  /* ——— Export ——— */
  { id: "e-free", q: "Is export included on the Free plan?", c: "export", k: "free export included csv plan",
    a: ["Yes — **CSV export is on every plan**, including Free. Your leads are never locked in."],
    f: ["csv-export", "export-fields", "plan-free"] },
  { id: "export-select", q: "Can I export only selected leads?", c: "export", k: "select selected some partial subset choose",
    a: ["Yes — export the visible selection or the whole list, and pick which fields to include."],
    f: ["export-fields", "l-segment", "csv-export"] },
  { id: "e-formats", q: "What formats can I export?", c: "export", k: "format excel json xlsx pdf type csv",
    a: ["**CSV** — the format every CRM, sequencer, and spreadsheet tool accepts."],
    f: ["export-fields", "e-crm", "csv-export"] },
  { id: "e-crm", q: "Can I get leads into my CRM?", c: "export", k: "crm import hubspot salesforce pipedrive tool",
    a: ["Export to CSV and import that file into your CRM — the supported path out of Zybble works with any tool that reads CSV."],
    f: ["e-formats", "export-fields", "l-crm"] },
  { id: "e-limit", q: "Is there an export limit?", c: "export", k: "limit export many times restriction cap",
    a: ["Export is included on every plan. The number of leads you can discover in a month is governed by your plan's allowance."],
    f: ["limits", "csv-export", "pricing-work"] },
  { id: "e-after-cancel", q: "Do I keep exports if I cancel?", c: "export", k: "cancel keep after downloaded leave lose",
    a: ["Files you've already exported are yours — they live on your machine, not in Zybble.", "Inside the product, saved lists and past exports remain accessible while your account exists."],
    f: ["billing", "acct-delete", "limit-reset"] },
];
