import type { Compact } from "./compact";

/**
 * Pack 1 — Getting started, product basics, lead discovery,
 * search phrasing, and industry/use-case examples.
 *
 * Answer line syntax: "# " heading · "- " list item · else paragraph.
 * Content rule: only facts stated elsewhere on the public site.
 */
export const PACK_PRODUCT: Compact[] = [
  /* ——— Getting started ——— */
  { id: "gs-start", q: "How do I get started?", c: "product", k: "start begin signup setup first",
    a: ["Start on the **Free plan ($0/mo)**, describe the businesses you need, and run a real search — 50 leads a month, no payment to evaluate.", "Everything runs in the browser; there's nothing to install."],
    cta: ["Start for free", "/#pricing"], f: ["gs-first-search", "example-search", "plan-free"] },
  { id: "gs-first-search", q: "What should my first search be?", c: "product", k: "first search try begin",
    a: ["Pick one category and one city you already know — “dentists in Austin”, “law firms in Denver”.", "A familiar market makes it easy to judge the quality of what comes back."],
    f: ["example-search", "search-phrasing", "lead-info"] },
  { id: "gs-install", q: "Do I need to install anything?", c: "product", k: "install download app software",
    a: ["No — Zybble runs in your browser."], f: ["gs-mobile", "gs-start", "how-find"] },
  { id: "gs-mobile", q: "Is there a mobile app?", c: "product", k: "mobile app phone ios android",
    a: ["Zybble is a web app you use in the browser."], f: ["gs-install", "how-find", "csv-export"] },
  { id: "gs-trial", q: "Is there a free trial?", c: "product", k: "trial free test evaluate",
    a: ["The **Free plan** is the way to try Zybble — $0/mo with 50 leads a month, phone and email data, 1 list, and CSV export.", "Upgrade only when you need more volume."],
    cta: ["View pricing", "/#pricing"], f: ["plan-free", "plan-growth", "pricing-work"] },
  { id: "gs-demo", q: "Can I see a demo?", c: "product", k: "demo walkthrough show call",
    a: ["Ask for a product demo through the contact page and a person will get back to you within one business day."],
    cta: ["Contact us", "/contact"], f: ["contact", "gs-start", "example-search"] },
  { id: "gs-problem", q: "What problem does Zybble solve?", c: "product", k: "problem why purpose point",
    a: ["Finding targeted businesses is usually slow manual work — searching maps, copying details, cleaning duplicates.", "Zybble turns that into one sentence and returns structured, deduplicated leads."],
    f: ["gs-vs-spreadsheet", "how-find", "who-for"] },
  { id: "gs-vs-spreadsheet", q: "How is this better than a spreadsheet?", c: "product", k: "spreadsheet excel manual sheets",
    a: ["A spreadsheet stores what you've already found. Zybble **finds it**, structures it, removes duplicates, and enriches it.", "You can still export to CSV and work in a spreadsheet afterwards."],
    f: ["csv-export", "how-find", "lead-lists"] },
  { id: "gs-vs-scraping", q: "How is this different from scraping?", c: "product", k: "scrape scraping script bot crawler",
    a: ["No scripts to write or maintain. You describe what you want in plain language and Zybble handles the search, processing, and deduplication."],
    f: ["how-find", "lead-sources", "gs-vs-lists"] },
  { id: "gs-vs-lists", q: "Why not just buy a lead list?", c: "product", k: "buy purchase list database vendor",
    a: ["Bought lists are static and generic. Zybble builds a list **to your exact request** — category, location, and filters — using current public business data.", "You can re-run a search whenever the market changes."],
    f: ["lead-sources", "how-find", "lead-info"] },
  { id: "gs-workflow", q: "What does a typical workflow look like?", c: "product", k: "workflow routine process day",
    a: ["- Describe the businesses you need", "- Review the structured results", "- Save them into a tagged lead list", "- Analyze interesting ones with Zybble AI", "- Export to CSV and start outreach"],
    f: ["search-process", "lead-lists", "csv-export"] },
  { id: "gs-good-fit", q: "Is Zybble a good fit for me?", c: "product", k: "fit right suitable good for",
    a: ["If you work targeted lists of **businesses** — local services, agencies, clinics, shops, firms — Zybble is built for that.", "It finds businesses rather than individual consumers."],
    f: ["who-for", "gs-b2b", "industries-list"] },
  { id: "gs-b2b", q: "Is this for B2B?", c: "product", k: "b2b business sales prospecting",
    a: ["Yes — Zybble discovers businesses and their public contact details, which is the core of B2B prospecting."],
    f: ["who-for", "lead-info", "gs-workflow"] },
  { id: "gs-consumers", q: "Can it find individual people?", c: "product", k: "people consumers individuals b2c persons",
    a: ["Zybble finds **businesses**, not individual consumers. Leads are business records — name, category, location, and public contact details."],
    f: ["lead-info", "lead-sources", "gs-b2b"] },
  { id: "industries-list", q: "Which industries can it find?", c: "discovery", k: "industries verticals niches categories sectors",
    a: ["Any business category you can describe — dentists, restaurants, law firms, gyms, salons, contractors, hotels, agencies, clinics, retailers, and so on."],
    f: ["what-can-search", "ex-restaurants", "ex-agencies"] },
  { id: "gs-countries", q: "Does it work outside my country?", c: "discovery", k: "country international global worldwide region",
    a: ["You describe any location you want, and leads include a **country** field alongside the address and coordinates.", "Coverage depends on the public business data available for that area."],
    f: ["ex-location", "lead-info", "lead-sources"] },
  { id: "gs-upgrade-later", q: "Can I upgrade later?", c: "billing", k: "upgrade later change switch move",
    a: ["Yes — plans are monthly, so you can move up when your volume grows."],
    cta: ["View pricing", "/#pricing"], f: ["gs-downgrade", "pricing-work", "billing"] },
  { id: "gs-downgrade", q: "Can I downgrade?", c: "billing", k: "downgrade lower reduce cheaper switch",
    a: ["Yes. Plans are billed monthly with no long-term commitment, so you can change tiers between cycles."],
    f: ["billing", "pricing-work", "limit-reset"] },
  { id: "gs-speed", q: "How fast are results?", c: "discovery", k: "fast speed quick time long wait",
    a: ["Searches run, process, and deduplicate before the leads appear — you watch the progress as it happens.", "**Scale** adds priority lead processing for high-volume searches."],
    f: ["priority", "search-process", "plan-scale"] },
  { id: "gs-learning", q: "Is it hard to learn?", c: "product", k: "learn easy difficult simple training",
    a: ["If you can describe the businesses you want in a sentence, you can use Zybble. There's no query language to learn."],
    f: ["search-phrasing", "example-search", "gs-start"] },

  /* ——— Discovery mechanics ——— */
  { id: "search-phrasing", q: "How should I phrase a search?", c: "discovery", k: "phrase write word query syntax",
    a: ["Include three things: **what**, **where**, and **how many**.", "“Find 250 marketing agencies in Chicago” works. Add requirements like “with a website” or “rated above 4”."],
    f: ["example-search", "ex-filters", "what-can-search"] },
  { id: "ex-filters", q: "What filters can I use?", c: "discovery", k: "filter filters criteria requirements narrow",
    a: ["- Minimum rating (for example 4.0+)", "- Has a website", "- Has a phone number", "Filters are shown on the search so you can see and adjust them."],
    f: ["ex-rating", "search-phrasing", "lead-info"] },
  { id: "ex-rating", q: "Can I filter by rating?", c: "discovery", k: "rating stars reviews filter quality above",
    a: ["Yes — ask for something like “rated above 4” and Zybble applies it as a filter. Each lead also carries its rating and review count."],
    f: ["ex-reviews", "ex-filters", "lead-info"] },
  { id: "ex-reviews", q: "Can I find businesses by review count?", c: "discovery", k: "reviews count popular many volume",
    a: ["Leads include **review count** alongside the rating, so you can sort and segment by review volume once results are in."],
    f: ["ex-rating", "lead-info", "tags-notes"] },
  { id: "ex-website", q: "Can I find businesses without a website?", c: "discovery", k: "website no site missing without has",
    a: ["Website presence is one of the supported filters — you can require one. Each lead also shows whether a website was detected, so you can segment either direction after the search."],
    f: ["ex-filters", "lead-info", "tags-notes"] },
  { id: "ex-location", q: "How specific can the location be?", c: "discovery", k: "location city area neighborhood region radius",
    a: ["Describe it the way you'd say it — a city, a region, or a specific area. Leads come back with the full address, country, and coordinates."],
    f: ["ex-multi-city", "lead-info", "search-phrasing"] },
  { id: "ex-multi-city", q: "Can I search several cities?", c: "discovery", k: "multiple cities markets several many regions",
    a: ["Run a search per market and save each into its own lead list — for example “Austin Dentists” and “Denver Dentists”.", "Unlimited lists are included on every paid plan."],
    f: ["lead-lists", "unlimited-lists", "ex-location"] },
  { id: "ex-quantity", q: "How many leads can one search return?", c: "discovery", k: "how many quantity number amount size",
    a: ["You set the target in the request — “500 dentists in Austin”. The practical ceiling is your **monthly lead allowance**.", "Free covers 50 a month; Scale covers 50,000."],
    f: ["limits", "pricing-work", "ex-quantity-small"] },
  { id: "ex-quantity-small", q: "Can I run small searches?", c: "discovery", k: "small few handful test sample",
    a: ["Yes — ask for 10 or 25 to sanity-check a market before committing more of your monthly allowance."],
    f: ["limits", "example-search", "plan-free"] },
  { id: "dedupe", q: "Does it remove duplicates?", c: "discovery", k: "duplicate duplicates repeat same dedupe clean",
    a: ["Yes. Removing duplicates is a built-in step of every search, before the leads are presented."],
    f: ["search-process", "data-quality", "how-find"] },
  { id: "data-quality", q: "How accurate is the data?", c: "data", k: "accurate accuracy correct reliable quality stale",
    a: ["Leads reflect the **public business information available at search time** — listings, websites, and public profiles.", "Details change, so verify anything critical before outreach."],
    f: ["lead-sources", "data-freshness", "lead-info"] },
  { id: "data-freshness", q: "How current is the information?", c: "data", k: "fresh current updated recent old date",
    a: ["Each search pulls from current public business data rather than a frozen list, which is why re-running a search later can return updated details."],
    f: ["rerun-search", "data-quality", "lead-sources"] },
  { id: "rerun-search", q: "Can I re-run a search later?", c: "discovery", k: "rerun repeat again refresh update",
    a: ["Yes — run the same request again whenever you want a fresh view of a market. Each run counts toward your monthly lead allowance."],
    f: ["limits", "data-freshness", "lead-lists"] },
  { id: "partial-data", q: "What if a business has missing details?", c: "data", k: "missing empty blank incomplete null",
    a: ["The field stays empty rather than being guessed. Available fields vary per business depending on what's public."],
    f: ["lead-info", "enrichment-data", "data-quality"] },
  { id: "search-history", q: "Can I see past searches?", c: "lists", k: "history past previous saved searches recent",
    a: ["Save any search into a lead list and it stays available in your workspace — your saved lists and past exports remain accessible even if you hit a monthly limit."],
    f: ["lead-lists", "limit-reset", "save-results"] },

  /* ——— Industry examples ——— */
  { id: "ex-dentists", q: "How would I find dentists?", c: "discovery", k: "dentist dentists dental clinic medical",
    a: ["Try: “Find 500 dentists in Austin with websites and ratings above 4.”", "You'll get names, categories, addresses, phones, websites, ratings, and review counts."],
    f: ["lead-info", "ex-filters", "csv-export"] },
  { id: "ex-restaurants", q: "Can it find restaurants?", c: "discovery", k: "restaurant restaurants food cafe bar dining",
    a: ["Yes. Try: “Find 300 restaurants in Portland rated above 4.”", "Where available, leads can include hours and price level alongside the core business details."],
    f: ["lead-info", "ex-filters", "ex-hours"] },
  { id: "ex-agencies", q: "Can it find marketing agencies?", c: "discovery", k: "agency agencies marketing creative studio",
    a: ["Yes. Try: “Find 250 marketing agencies in Chicago.”", "Add “with a website” to focus on agencies with a direct outreach channel."],
    f: ["ex-filters", "lead-info", "agency-use"] },
  { id: "ex-contractors", q: "Can it find contractors or trades?", c: "discovery", k: "contractor plumber electrician roofing trades hvac",
    a: ["Yes — plumbers, electricians, roofers, HVAC, and similar trades are all business categories you can describe.", "Try: “Find 200 plumbers in Phoenix with phone numbers.”"],
    f: ["ex-filters", "lead-info", "example-search"] },
  { id: "ex-gyms", q: "Can it find gyms and fitness studios?", c: "discovery", k: "gym gyms fitness studio yoga pilates",
    a: ["Yes. Try: “Find 150 gyms in Miami rated above 4.5.”"],
    f: ["ex-rating", "lead-info", "csv-export"] },
  { id: "ex-salons", q: "Can it find salons and spas?", c: "discovery", k: "salon spa barber beauty hair nails",
    a: ["Yes. Try: “Find 200 hair salons in Nashville with websites.”"],
    f: ["ex-filters", "lead-info", "lead-lists"] },
  { id: "ex-realestate", q: "Can it find real estate offices?", c: "discovery", k: "real estate realtor broker property agent",
    a: ["Yes — describe the category and market, for example “Find 150 real estate brokerages in Tampa.”"],
    f: ["lead-info", "ex-location", "csv-export"] },
  { id: "ex-medical", q: "Can it find clinics and medical practices?", c: "discovery", k: "clinic medical doctor practice health dermatology vet",
    a: ["Yes — clinics, practices, specialists, and veterinary offices are all describable categories.", "Try: “Find 300 veterinary clinics in Ohio with phone numbers.”"],
    f: ["ex-filters", "lead-info", "example-search"] },
  { id: "ex-legal", q: "Can it find law firms?", c: "discovery", k: "law firm lawyer attorney legal practice",
    a: ["Yes. Try: “Find 200 family law firms in Denver rated above 4.”"],
    f: ["ex-rating", "lead-info", "csv-export"] },
  { id: "ex-hotels", q: "Can it find hotels?", c: "discovery", k: "hotel hotels hospitality motel inn lodging",
    a: ["Yes. Try: “Find 100 boutique hotels in Oregon.”", "Hotel records can include rating, review count, and hours where available."],
    f: ["lead-info", "ex-filters", "ex-location"] },
  { id: "ex-retail", q: "Can it find retail shops?", c: "discovery", k: "retail shop store boutique ecommerce",
    a: ["Yes — describe the type of shop and the market, for example “Find 250 furniture stores in Atlanta.”"],
    f: ["lead-info", "ex-location", "csv-export"] },
  { id: "ex-ecommerce", q: "Can it find online businesses?", c: "discovery", k: "online ecommerce internet web store digital",
    a: ["Zybble discovers businesses from public business listings, which skews toward companies with a physical or listed presence.", "Every lead shows whether a website was detected."],
    f: ["lead-sources", "ex-website", "lead-info"] },
  { id: "ex-hours", q: "Can I see opening hours?", c: "data", k: "hours opening times schedule open closed",
    a: ["Yes — opening hours are part of the business record where they're available."],
    f: ["lead-info", "partial-data", "ex-coords"] },
  { id: "ex-coords", q: "Do leads include coordinates?", c: "data", k: "coordinates gps latitude longitude map location",
    a: ["Yes — each lead carries coordinates alongside its address and country, which is useful for mapping or territory planning."],
    f: ["lead-info", "export-fields", "ex-location"] },
  { id: "ex-price-level", q: "Is price level included?", c: "data", k: "price level cost expensive cheap tier",
    a: ["Price level is part of the business record where the underlying data provides it."],
    f: ["lead-info", "partial-data", "ex-hours"] },
  { id: "ex-services", q: "Are services or amenities included?", c: "data", k: "services amenities features offerings attributes",
    a: ["Services and amenities appear where the available business data includes them — coverage varies by business."],
    f: ["lead-info", "partial-data", "data-quality"] },
  { id: "ex-category-field", q: "What is the category field?", c: "data", k: "category type classification kind business types",
    a: ["It's how the business is classified — “Dentist”, “Cosmetic dentist”, “Orthodontist”. Leads can carry multiple business types."],
    f: ["lead-info", "what-can-search", "tags-notes"] },
];
