import type { Compact } from "./compact";

/** Pack 3 — Pricing, limits, teams, workspaces, billing, privacy, support. */
export const PACK_PLANS: Compact[] = [
  /* ——— Plan comparison ——— */
  { id: "p-compare", q: "What's the difference between plans?", c: "pricing", k: "difference compare versus between plans",
    a: ["Volume, lists, and seats (Zybble AI is on every plan):", "- **Free ₹0** — 50 leads, Zybble AI, 1 list, 1 user", "- **Growth ₹49** — 5,000 leads, unlimited lists, 1 user", "- **Agency ₹99** — 15,000 leads, 3 members, client workspaces", "- **Scale ₹199** — 50,000 leads, 5 members, priority processing"],
    cta: ["View pricing", "/#pricing"], f: ["p-free-vs-growth", "p-agency-vs-scale", "which-plan"] },
  { id: "p-free-vs-growth", q: "Free or Growth — what changes?", c: "pricing", k: "free growth difference upgrade compare",
    a: ["Growth (₹49/mo) raises leads from **50 to 5,000 a month** and makes lead lists **unlimited**.", "Both are single-user, and both include Zybble AI, phone and email data, plus CSV export."],
    cta: ["View pricing", "/#pricing"], f: ["plan-growth", "ai-availability", "p-compare"] },
  { id: "p-growth-vs-agency", q: "Growth or Agency — what changes?", c: "pricing", k: "growth agency difference compare team",
    a: ["Agency (₹99/mo) triples volume to **15,000 leads**, adds **3 team members**, and adds **client workspaces**.", "Everything in Growth carries over."],
    cta: ["View pricing", "/#pricing"], f: ["plan-agency", "workspaces", "team-use"] },
  { id: "p-agency-vs-scale", q: "Agency or Scale — what changes?", c: "pricing", k: "agency scale difference compare bigger",
    a: ["Scale (₹199/mo) raises volume from 15,000 to **50,000 leads**, seats from 3 to **5 team members**, and adds **priority lead processing**.", "Client workspaces are on both."],
    cta: ["View pricing", "/#pricing"], f: ["plan-scale", "priority", "workspaces"] },
  { id: "p-most-popular", q: "Which plan is most popular?", c: "pricing", k: "popular common most chosen recommended",
    a: ["**Agency (₹99/mo)** is marked as the most popular option on the pricing page — it's the first tier with team members and client workspaces."],
    cta: ["View pricing", "/#pricing"], f: ["plan-agency", "p-compare", "which-plan"] },
  { id: "p-solo", q: "I work alone — which plan fits?", c: "pricing", k: "solo alone freelancer single one person myself",
    a: ["Free and Growth are both single-user. **Free** covers 50 leads a month; **Growth (₹49/mo)** covers 5,000 with unlimited lists. Zybble AI is on both."],
    cta: ["View pricing", "/#pricing"], f: ["plan-free", "plan-growth", "p-free-vs-growth"] },
  { id: "p-startup", q: "I'm a startup finding first customers", c: "pricing", k: "startup founder first customers early small",
    a: ["Start Free to validate that Zybble finds your market, then move to **Growth (₹49/mo)** when 50 leads a month stops being enough."],
    cta: ["Start for free", "/#pricing"], f: ["plan-free", "plan-growth", "gs-first-search"] },
  { id: "p-sales-team", q: "I run a sales team", c: "pricing", k: "sales team reps outbound sdr pipeline",
    a: ["Seats start on **Agency (₹99/mo)** with 3 team members and 15,000 leads; **Scale (₹199/mo)** covers 5 members and 50,000 leads."],
    cta: ["View pricing", "/#pricing"], f: ["team-use", "plan-agency", "plan-scale"] },
  { id: "p-need-workspaces", q: "I need client workspaces", c: "workspaces", k: "client workspaces need separate agency",
    a: ["Client workspaces are included on **Agency (₹99/mo)** and **Scale (₹199/mo)**.", "They keep each client's searches, lists, and exports separate under one account."],
    cta: ["View pricing", "/#pricing"], f: ["workspaces", "plan-agency", "plan-scale"] },
  { id: "p-need-15000", q: "I need around 15,000 leads", c: "pricing", k: "15000 15,000 volume need amount",
    a: ["That's **Agency — ₹99/mo**: 15,000 leads a month, 3 team members, client workspaces, and unlimited lists."],
    cta: ["View pricing", "/#pricing"], f: ["plan-agency", "limits", "p-agency-vs-scale"] },
  { id: "p-need-small", q: "I only need a few hundred leads", c: "pricing", k: "few hundred small low volume little",
    a: ["**Growth (₹49/mo)** covers 5,000 leads a month, so a few hundred sits comfortably inside it.", "If it's closer to 50 a month, Free may be enough — Zybble AI is on every plan."],
    cta: ["View pricing", "/#pricing"], f: ["plan-growth", "plan-free", "limits"] },
  { id: "p-over-50k", q: "What if I need more than 50,000?", c: "pricing", k: "more than 50000 enterprise custom higher bigger",
    a: ["**Scale (₹199/mo)** is the largest listed plan, at 50,000 leads a month with priority processing.", "For anything beyond that, the contact page is the right place to ask."],
    cta: ["Contact us", "/contact"], f: ["plan-scale", "contact", "priority"] },
  { id: "p-annual", q: "Is there an annual plan?", c: "billing", k: "annual yearly year discount prepay",
    a: ["Pricing is **monthly only** — the four listed plans are billed month to month with no annual commitment."],
    f: ["billing", "pricing-work", "p-discounts"] },
  { id: "p-discounts", q: "Are there discounts?", c: "billing", k: "discount coupon promo deal offer cheaper student",
    a: ["The published pricing is the four monthly plans shown on the pricing page. If you have a specific situation, ask through the contact page."],
    cta: ["View pricing", "/#pricing"], f: ["pricing-work", "contact", "p-annual"] },
  { id: "p-hidden-fees", q: "Are there hidden fees?", c: "billing", k: "hidden fees extra charges surprise additional",
    a: ["The plan price is what's listed — ₹0, ₹49, ₹99, or ₹199 a month, each with the leads and features shown on the pricing page."],
    cta: ["View pricing", "/#pricing"], f: ["pricing-work", "billing", "limits"] },
  { id: "p-per-lead", q: "Do I pay per lead?", c: "billing", k: "per lead credit cost each unit pay",
    a: ["No — you pay a flat monthly plan price, and each plan includes a monthly lead allowance."],
    f: ["limits", "pricing-work", "p-hidden-fees"] },

  /* ——— Limits ——— */
  { id: "u-rollover", q: "Do unused leads roll over?", c: "usage", k: "rollover unused carry over next month remaining",
    a: ["No — monthly allowances reset at the start of each cycle and don't roll over."],
    f: ["limits", "limit-reset", "pricing-work"] },
  { id: "u-counts", q: "What counts against my limit?", c: "usage", k: "count counts toward usage consume uses",
    a: ["Leads discovered through searches draw on your monthly allowance. Re-running the same search counts again, since it pulls fresh data."],
    f: ["rerun-search", "limits", "u-rollover"] },
  { id: "u-track", q: "Can I see my usage?", c: "usage", k: "usage track remaining left monitor how much",
    a: ["Your plan's monthly allowance governs how much discovery you can run, and searches pause once it's reached until the cycle resets."],
    f: ["limit-reset", "limits", "u-rollover"] },
  { id: "u-exceeded", q: "Can I buy more leads mid-month?", c: "usage", k: "buy more extra top up additional midmonth",
    a: ["The listed path to more volume is moving to a plan with a larger allowance — Growth, Agency, or Scale.", "Allowances also reset at the start of each monthly cycle."],
    cta: ["View pricing", "/#pricing"], f: ["pricing-work", "limit-reset", "gs-upgrade-later"] },
  { id: "u-shared", q: "Is the limit shared across my team?", c: "usage", k: "shared team pooled members split allowance",
    a: ["The allowance belongs to the plan — Agency covers 15,000 leads a month across 3 team members, Scale 50,000 across 5."],
    f: ["team-use", "limits", "plan-scale"] },

  /* ——— Teams & workspaces ——— */
  { id: "t-add", q: "How do I add team members?", c: "team", k: "add invite member seat teammate colleague",
    a: ["Seats come with the plan: **Agency** includes 3 team members, **Scale** includes 5. Free and Growth are single-user."],
    cta: ["View pricing", "/#pricing"], f: ["team-use", "plan-agency", "t-more-seats"] },
  { id: "t-more-seats", q: "Can I add more than 5 seats?", c: "team", k: "more seats extra additional beyond five",
    a: ["Scale's listed allocation is 5 team members — the largest on the pricing page. For a larger team, ask through the contact page."],
    cta: ["Contact us", "/contact"], f: ["plan-scale", "contact", "team-use"] },
  { id: "t-share-login", q: "Can we share one login?", c: "team", k: "share login password account single credentials",
    a: ["No — plans include the users and team members shown on the pricing page, and sharing a single login isn't permitted.", "Agency and Scale exist for multi-person teams."],
    f: ["team-use", "plan-agency", "terms-link"] },
  { id: "w-how-many", q: "How many client workspaces can I have?", c: "workspaces", k: "how many workspaces clients number limit",
    a: ["Client workspaces are included with **Agency** and **Scale** to keep each client's searches, lists, and exports separate under one account."],
    cta: ["View pricing", "/#pricing"], f: ["workspaces", "plan-agency", "plan-scale"] },
  { id: "w-client-access", q: "Can clients see their workspace?", c: "workspaces", k: "client access login see view share report",
    a: ["Workspaces organize work **for your team** — each client's searches, lists, and exports stay separated. To hand results over, export the list to CSV."],
    f: ["csv-export", "workspaces", "agency-use"] },
  { id: "w-white-label", q: "Is there white labeling?", c: "workspaces", k: "white label branding rebrand logo reseller",
    a: ["The listed agency features are **client workspaces** plus team seats on Agency and Scale. For anything beyond that, ask through the contact page."],
    cta: ["Contact us", "/contact"], f: ["workspaces", "contact", "agency-use"] },

  /* ——— Billing & account ——— */
  { id: "b-payment", q: "How do payments work?", c: "billing", k: "payment card pay method billing charge",
    a: ["Plans are billed **monthly in advance**. Payment details are handled by the payment provider and aren't stored on Zybble's servers."],
    f: ["billing", "security", "p-hidden-fees"] },
  { id: "b-cancel-effect", q: "When does cancellation take effect?", c: "billing", k: "cancel effect when end period stop",
    a: ["At the **end of your current billing period** — you keep access until then."],
    f: ["billing", "e-after-cancel", "acct-delete"] },
  { id: "b-refund", q: "What about refunds?", c: "billing", k: "refund money back return reimburse",
    a: ["Plans are monthly with no long-term commitment, and cancelling takes effect at the end of the current period.", "For a specific billing question, the contact page reaches a person."],
    cta: ["Contact us", "/contact"], f: ["b-cancel-effect", "billing", "contact"] },
  { id: "acct-delete", q: "How do I delete my account?", c: "security", k: "delete account close remove erase gdpr",
    a: ["Deleting your account deletes your searches, lead lists, and exports, and backups are purged on a rolling schedule.", "Export anything you want to keep first."],
    cta: ["Read the privacy policy", "/privacy"], f: ["security", "csv-export", "b-cancel-effect"] },
  { id: "acct-age", q: "Is there an age requirement?", c: "security", k: "age 18 old requirement eligible minimum",
    a: ["You must be at least 18 to use Zybble."],
    cta: ["Read the terms", "/terms"], f: ["terms-link", "security", "contact"] },

  /* ——— Privacy, security, compliance ——— */
  { id: "s-sell-data", q: "Do you sell my data?", c: "security", k: "sell share data third party privacy resell",
    a: ["No. Zybble doesn't sell your personal information, and your lead lists and exports are never shared with other customers."],
    cta: ["Read the privacy policy", "/privacy"], f: ["security", "s-what-stored", "acct-delete"] },
  { id: "s-what-stored", q: "What data do you store about me?", c: "security", k: "store keep collect data about me personal",
    a: ["- Account details — name, email, password stored only as a secure hash", "- Plan and billing metadata (payments handled by the provider)", "- Usage — your searches, lists, and exports", "- Support conversations you send us"],
    cta: ["Read the privacy policy", "/privacy"], f: ["s-sell-data", "acct-delete", "security"] },
  { id: "s-lawful-use", q: "Can I use leads for cold outreach?", c: "security", k: "cold outreach email legal spam compliance gdpr allowed",
    a: ["You own your saved lists and exports and can use them **in line with applicable law**. Zybble's terms prohibit unlawful outreach, spam, and harassment.", "Outreach rules vary by country — follow the ones that apply to you."],
    cta: ["Read the terms", "/terms"], f: ["terms-link", "s-resell", "d-verify"] },
  { id: "s-resell", q: "Can I resell the lead data?", c: "security", k: "resell sell data third parties redistribute",
    a: ["No — reselling raw lead data to third parties isn't permitted under the terms.", "Using leads for your own outreach, or your clients' campaigns through workspaces, is what the product is for."],
    cta: ["Read the terms", "/terms"], f: ["terms-link", "workspaces", "s-lawful-use"] },
  { id: "s-public-data", q: "Is the business data public?", c: "security", k: "public legal source permitted scraped rights",
    a: ["Leads are assembled from **publicly available business information** — listings, business websites, and public profiles."],
    f: ["lead-sources", "s-lawful-use", "data-quality"] },
  { id: "terms-link", q: "Where can I read the terms?", c: "security", k: "terms legal policy agreement contract conditions",
    a: ["The full Terms of Service cover accounts, fair use, acceptable use, data ownership, billing, and cancellation."],
    cta: ["Read the terms", "/terms"], f: ["security", "s-lawful-use", "contact"] },
  { id: "privacy-link", q: "Where can I read the privacy policy?", c: "security", k: "privacy policy data gdpr read",
    a: ["The Privacy Policy covers what's collected, how it's used, how long it's kept, and the control you keep over it."],
    cta: ["Read the privacy policy", "/privacy"], f: ["s-what-stored", "acct-delete", "security"] },

  /* ——— Support ——— */
  { id: "sup-response", q: "How fast do you reply to support?", c: "support", k: "support reply response time fast help wait",
    a: ["A person reads every message, and replies typically arrive **within one business day**."],
    cta: ["Contact us", "/contact"], f: ["contact", "sup-priority", "gs-demo"] },
  { id: "sup-priority", q: "Is there priority support?", c: "support", k: "priority support premium dedicated faster sla",
    a: ["The listed priority feature is **priority lead processing** on Scale, which moves large searches ahead of the standard queue.", "For support, every message reaches a person through the contact page."],
    f: ["priority", "contact", "plan-scale"] },
  { id: "sup-feature", q: "Can I request a feature?", c: "support", k: "feature request suggest idea roadmap feedback",
    a: ["Yes — send it through the contact page. Product feedback goes to a human who reads it."],
    cta: ["Contact us", "/contact"], f: ["contact", "sup-response", "gs-demo"] },
  { id: "sup-partnership", q: "Do you do partnerships?", c: "support", k: "partner partnership affiliate reseller collaborate",
    a: ["Partnership is one of the topics on the contact form — send the details and a person will reply."],
    cta: ["Contact us", "/contact"], f: ["contact", "w-white-label", "sup-feature"] },
  { id: "sup-bug", q: "Something isn't working — what do I do?", c: "support", k: "bug broken issue problem error not working help",
    a: ["Send what you were doing and what happened through the contact page. Support is one of the listed topics, and a person replies within about a business day."],
    cta: ["Contact us", "/contact"], f: ["contact", "sup-response", "sup-feature"] },
];
